.TH "Client" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Client \- Class representing the \fBClient\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Client\&.hpp>\fP
.SH "Detailed Description"
.PP 
Class representing the \fBClient\fP\&. 

This class handle the \fBClient\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
