.TH "ClientDatabase" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientDatabase \- Class representing the \fBClientDatabase\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientDatabase\&.hpp>\fP
.SH "Detailed Description"
.PP 
Class representing the \fBClientDatabase\fP\&. 

This class handle the \fBClientDatabase\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
