.TH "ClientActions" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClientActions \- Class representing the \fBClientActions\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ClientActions\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBinfo_s\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBsendInfos\fP (const \fBinfo_s\fP &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class representing the \fBClientActions\fP\&. 

This class handle the \fBClientActions\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
