.TH "Data" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Data \- Class representing the \fBData\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Data\&.hpp>\fP
.SH "Detailed Description"
.PP 
Class representing the \fBData\fP\&. 

This class handle the \fBData\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
