.TH "EncoderSystem" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncoderSystem
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBencoderCreate\fP ()"
.br
.ti -1c
.RI "bool \fBdecoderCreate\fP ()"
.br
.ti -1c
.RI "unsigned char * \fBencode\fP (unsigned char *, int)"
.br
.ti -1c
.RI "unsigned char * \fBdecode\fP (unsigned char *, int)"
.br
.ti -1c
.RI "int \fBgetEncodeLen\fP () const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
