.TH "mainWindow" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBtakeIp\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
