.TH "paTestData" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
paTestData
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBframeIndex\fP"
.br
.ti -1c
.RI "int \fBmaxFrameIndex\fP"
.br
.ti -1c
.RI "float * \fBrecordedSamples\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
