.TH "PortAudio" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PortAudio
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetInputParameters\fP ()"
.br
.ti -1c
.RI "void \fBSetOutputParameters\fP ()"
.br
.ti -1c
.RI "void \fBSetData\fP (int, int, int)"
.br
.ti -1c
.RI "void \fBStartStream\fP (PaStream *)"
.br
.ti -1c
.RI "void \fBCloseStream\fP (PaStream *)"
.br
.ti -1c
.RI "PaStream * \fBRecordStream\fP ()"
.br
.ti -1c
.RI "void \fBPlayStream\fP (PaStream *)"
.br
.ti -1c
.RI "void \fBsetSampleRate\fP (short)"
.br
.ti -1c
.RI "void \fBsetFramePerBuffer\fP (short)"
.br
.ti -1c
.RI "void \fBsetDataFrameIndex\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
