.TH "Server" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Server \- Class representing the \fBServer\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Server\&.hpp>\fP
.SH "Detailed Description"
.PP 
Class representing the \fBServer\fP\&. 

This class handle of the logic of the program, it loads the libraires and the protocols it can switch at any given moments 

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
