.TH "ServerClient" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerClient \- Class representing the \fBServerClient\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerClient\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerClient\fP (\fBSocket\fP sock)"
.br
.ti -1c
.RI "std::string \fBgetUsername\fP () const noexcept"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSocket\fP \fB_sock\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class representing the \fBServerClient\fP\&. 

This class handle the server's clients 

.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
