.TH "Ui::MainWindow" 3 "Sun Oct 13 2019" "Version Alpha 1.2" "Babel_2019" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Babel_2019 from the source code\&.
